version: "3"
services:
    api:
        image: friendapi-profiling
        container_name: friendapi-profiling
        build:
            context: .
            dockerfile: ./Dockerfile.Profiling
        volumes:
            - ./snapshots:/snapshots
        networks:
            - dbnet
            - apinet
        depends_on:
            - db  
        environment:
            - ASPNETCORE_ENVIRONMENT=compose
        ports:    
            - "5001:80"     
    db:
        image: custom-mssql
        container_name: custom-mssql
        build:
            context: ./database
            dockerfile: Dockerfile
        networks:
            - dbnet
        ports:
            - "1433:1433"      
    wrk6async:
        image: skandyla/wrk
        container_name: wrk6async
        networks:
            - apinet
        depends_on:
            - api  
        # entrypoint: sleep 30 && wrk
        entrypoint: sh -c "sleep 10 && wrk -t3 -c5 -d10s --latency http://api/friends"
        
    
networks:
    dbnet:
        name: dbnet
    apinet:
        name: apinet
        
